repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - files: ^src/
    id: black
  repo: https://github.com/psf/black
  rev: 23.1.0
- hooks:
  - files: ^src/
    id: isort
  repo: https://github.com/pycqa/isort
  rev: 5.12.0
- hooks:
  - id: commitizen
  # - id: commitizen-branch
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.1
  stages:
  - push
